image: brettbj/continuous_analysis_base:latest
script:
  - cd /var/cache/drone/src/github.com/greenelab/continuous_analysis
  - mkdir drone
  - nose2 --plugin nose2.plugins.junitxml --junit-xml test
  - mv nose2-junit.xml drone/tests.xml
  - coverage run --branch test.py
  - coverage xml -o drone/coverage.xml test.py

  - cd /kallisto/
  - /kallisto/build/src/kallisto index -i transcripts.idx transcripts.fasta.gz
  - /kallisto/build/src/kallisto quant -i transcripts.idx -o output -b 100 reads_1.fastq.gz reads_2.fastq.gz
  - mv /kallisto/build/src/kalllisto/output /var/cache/drone/src/github.com/greenelab/continuous_analysis/drone/output

  - cd /var/cache/drone/src/github.com/greenelab/continuous_analysis
  - git add drone/*
  - git commit -a -m "Drone Run"
  - git push
  
# commented out - because this is already done in shippable builds
# publish:
#   docker:
#     username: username
#     password: password
#     email: email@email.com
#     repo: brettbj/continuous_analysis
