image: brettbj/continuous_analysis_base:latest
script:
  - cd /var/cache/drone/src/github.com/greenelab/continuous_analysis
  - mkdir -p drone
  - nose2 --plugin nose2.plugins.junitxml --junit-xml test
  - mv nose2-junit.xml drone/tests.xml
  - coverage run --branch test.py
  - coverage xml -o drone/coverage.xml test.py

  # run kallisto on a few simple tests
  - cd /kallisto/test
  - kallisto index -i transcripts.idx transcripts.fasta.gz
  - kallisto quant -i transcripts.idx -o output -b 100 reads_1.fastq.gz reads_2.fastq.gz
  - cp -R /kallisto/test/output /var/cache/drone/src/github.com/greenelab/continuous_analysis/drone/output
  
  # plot the results from a jupyter notebook
  - cd /var/cache/drone/src/github.com/greenelab/continuous_analysis
  - jupyter nbconvert --to html --execute ./Drone_Plotting.ipynb

  # push the results back to github
  - git config user.email "brettbj@gmail.com"
  - git config user.name "Brett Beaulieu-Jones"
  - git config --global push.default simple
  - git remote set-url origin https://brettbj:$$git_publish_key@github.com/greenelab/continuous_analysis.git
  
  - git checkout master
  - git pull
  - git merge --no-ff staging -Xtheirs
  - git add drone/*
  - git commit drone/* -m "Drone output [CI SKIP] [SKIP CI] ."
  - git stash
  - git push

# commented out - because this is already done in shippable builds
# publish:
#   docker:
#     username: username
#     password: password
#     email: email@email.com
#     repo: brettbj/continuous_analysis
