language: python
sudo: required

services:
  - docker

before_install:
  - docker pull brettbj/continuous_analysis_base
  - docker run -it -d brettbj/continuous_analysis_base bin/bash

script:
  - ls
  - cd kallisto/test
  - kallisto index -i transcripts.idx transcripts.fasta.gz