language: bash
sudo: required

services:
  - docker

before_install:
  - mkdir -p travis-ci
  - docker pull brettbj/continuous_analysis_base
  - docker run --name con_test -t -d -v /home/travis/build/alexwhan/continuous_analysis:/continuous_analysis brettbj/continuous_analysis_base bin/bash

script:
  - ls
  - pwd
  - docker exec con_test pwd
  - docker exec con_test kallisto index -i kallisto/test/transcripts.idx kallisto/test/transcripts.fasta.gz
  - docker exec con_test kallisto quant -i kallisto/test/transcripts.idx -o output -b 100 kallisto/test/reads_1.fastq.gz kallisto/test/reads_2.fastq.gz
  - docker cp con_test:/kallisto/test/output 