language: python
sudo: required

services:
  - docker

before_install:
  - docker pull brettbj/continuous_analysis_base
  - docker run --name con_test -it -d brettbj/continuous_analysis_base bin/bash

script:
  - docker exec con_test kallisto index -i kallisto/test/transcripts.idx kallisto/test/transcripts.fasta.gz