language: bash
sudo: required

services:
  - docker

before_install:
  - docker pull brettbj/continuous_analysis_base

script:
  - docker run --name con_test -it brettbj/continuous_analysis_base bin/bash
  - kallisto index -i kallisto/test/transcripts.idx kallisto/test/transcripts.fasta.gz