language: python
sudo: required

services:
  - docker

before_install:
  - docker build -t alexwhan/cont_analysis_test .
  - docker run alexwhan/cont_analysis_test /bin/sh

script:
  - cd /kallisto/test
  - kallisto index -i transcripts.idx transcripts.fasta.gz