language: python
sudo: required

services:
  - docker

before_install:
  - docker pull brettbj/continuous_analysis_base
  - docker run brettbj/continuous_analysis_base /bin/sh -c "cd /kallisto test"

script:
  - ls
  - kallisto index -i transcripts.idx transcripts.fasta.gz